// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoGamesEcommerce.Data;

namespace ProjetoGamesEcommerce.Migrations
{
    [DbContext(typeof(EcommerceJogosContext))]
    [Migration("20210803165347_InicialEntities")]
    partial class InicialEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EcommerceJogosEntities.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Complemento");

                    b.Property<string>("Email");

                    b.Property<string>("Endereco");

                    b.Property<string>("Municipio");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.Property<string>("Uf");

                    b.HasKey("Id");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("EcommerceJogosEntities.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PedidoId");

                    b.Property<double>("PrecoUnitario");

                    b.Property<int?>("ProdutoId");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemPedidos");
                });

            modelBuilder.Entity("EcommerceJogosEntities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CadastroId");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("EcommerceJogosEntities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Codigo");

                    b.Property<string>("Nome");

                    b.Property<double>("Preco");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EcommerceJogosEntities.ItemPedido", b =>
                {
                    b.HasOne("EcommerceJogosEntities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId");

                    b.HasOne("EcommerceJogosEntities.Produto", "Produto")
                        .WithMany("Items")
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("EcommerceJogosEntities.Pedido", b =>
                {
                    b.HasOne("EcommerceJogosEntities.Cadastro", "Cadastro")
                        .WithMany("Pedidos")
                        .HasForeignKey("CadastroId");
                });
#pragma warning restore 612, 618
        }
    }
}
